cache.fixed.delay: 3600000

server:
  port: 8585

openweathermap:
  url: http://samples.openweathermap.org/data/2.5/forecast
#  url: http://api.openweathermap.org/data/2.5/weather
  appid: b6907d289e10d714a6e88b30761fae22

---

spring:
  profiles: test
  port: 8686

cache.fixed.delay: 2000
